on:
  push:

jobs:
  test-maven:
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'eclipse-temurin'
          java-version: '21'
      - name: setup maven
        uses: actionctl/setup-maven-cli@v1
      - name: test maven
        run: mvn -version
